name: JustArchi.net-publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2.3.1
      with:
        key: ${{ secrets.WEBSITE_DEPLOYMENT_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.WEBSITE_DEPLOYMENT_SSH_KNOWN_HOSTS }}
        name: id_ed25519

    - name: Deploy to server
      env:
        WEBSITE_DEPLOYMENT_PORT: ${{ secrets.WEBSITE_DEPLOYMENT_PORT }}
        WEBSITE_DEPLOYMENT_SERVER: ${{ secrets.WEBSITE_DEPLOYMENT_SERVER }}
        WEBSITE_DEPLOYMENT_USER: ${{ secrets.WEBSITE_DEPLOYMENT_USER }}
      shell: sh
      run: |
        set -eu

        ssh -p "$WEBSITE_DEPLOYMENT_PORT" -T "${WEBSITE_DEPLOYMENT_USER}@${WEBSITE_DEPLOYMENT_SERVER}" <<EOF
            set -eu

            flock -w 60 "/tmp/${{ secrets.WEBSITE_DEPLOYMENT_USER }}" ./JustArchi.net/deploy.sh
        EOF
